"""add health monitoring fields to sources

Revision ID: b4497266cbef
Revises: 7d725c48738d
Create Date: 2026-03-13 20:44:30.076906

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4497266cbef'
down_revision: str | Sequence[str] | None = '7d725c48738d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('health_status', sa.String(length=20), nullable=False, server_default='healthy'))
    op.add_column('sources', sa.Column('consecutive_failures', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('sources', sa.Column('last_health_check', sa.DateTime(), nullable=True))
    op.add_column('sources', sa.Column('last_healthy_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'last_healthy_at')
    op.drop_column('sources', 'last_health_check')
    op.drop_column('sources', 'consecutive_failures')
    op.drop_column('sources', 'health_status')
    # ### end Alembic commands ###
